### PR TITLE
Add `format` to support MDX and plain markdown

### PR DESCRIPTION
**Pull request by wooorm**
Add `format` to support MDX and plain markdown

* Default to detecting whether input is `mdx` or `md` based on whether the given
  file has an extension in `mdExtensions` and to handle both `mdExtensions` and
  `mdxExtensions` in integrations
* Support `format: 'md'` to treat input as markdown and to handle `mdExtensions`
  in integrations
* Support `format: 'mdx'` to treat input as MDX and to handle `mdxExtensions`
  in integrations
* Switch which elements will turn into configurable components, previously that
  was everything that was written in the source markdown, now this is everything
  not explicitly written as JSX
* Add tests for integration with `rehype-raw`
* Fix docs on `evaluate` options

Closes GH-17.

### CODE REVIEW

**Review by ChristianMurphy — APPROVED** [review]

**Comment by wooorm** [comment]
@ChristianMurphy Do you see the default being `detect` as a good idea? I *think* so

**Comment by ChristianMurphy** [comment]
> Do you see the default being detect as a good idea?

I think so. :+1: 
There is an edge case, that being if people use non-standard md and mdx extensions and still want the type to be inferred there isn't a way to override at the moment.
But until that use case pops up, [YAGNI](https://en.wikipedia.org/wiki/You_aren't_gonna_need_it)

**Comment by wooorm** [comment]
> There is an edge case, that being if people use non-standard md and mdx extensions and still want the type to be inferred there isn't a way to override at the moment.

The way I’ve set it up now is that there’s two lists of extensions: one for markdown, one for mdx. Folks can overwrite those to set their own funky preferences.

It’s indeed a weird case, but with `{mdExtensions: ['.mdx', ...], mdxExtensions: [...]}` one could load `.mdx` as markdown, or with `{mdExtensions: [...], mdxExtensions: ['.md', ...]}` one could set `.md` as MDX. Again, I think it’s really weird, but it’s *possible*.

**Comment by remcohaszing** [comment]
I mostly looked at the docs, because although I’ve looked at the internals, I’m not very familiar with them.

Anyway, looks good to me :+1:

**Pull request merged**
