### PR TITLE
fix astring

### PR DESCRIPTION
**Pull request by kentcdodds**
Fixes https://github.com/kentcdodds/mdx-bundler/issues/15
Fixes https://github.com/kentcdodds/mdx-bundler/issues/18

### CODE REVIEW

**Comment by kentcdodds** [comment]
Alternative solution: #35

**Comment by kentcdodds** [comment]
Hmmm... Not sure what's wrong. Based on what's on npm this should work 🤔

**Comment by wooorm** [comment]
Heya! we detected a broken patch in astring yesterday (https://github.com/davidbonnet/astring/issues/505), it was fixed 19 hours ago: https://github.com/davidbonnet/astring/commit/6d8a12240fef71defa281f7bb394eb2fcaee4dce. So, `npm update` should do the trick?

And: it was export maps and ESM 😅

**Comment by wooorm** [comment]
You caught me right before heading out. I’ll take my laptop with me, so do let me know if I need to land a hotfix!

**Comment by kentcdodds** [comment]
Ah, gotcha. I'll let folks know that `npm update` should fix it for them. Thanks!

**Comment by wooorm** [comment]
I think the fix in astring makes this PR superfluous, so I’ll close these two.

For anyone else stumbling on this, please try `npm update`, and let me know if that doesn’t fix it!

**Pull request closed without merging**
