### PR TITLE
types: add jsdoc types for astring generator

### PR DESCRIPTION
**Pull request by ChristianMurphy**

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
:thinking: there appear to be some uses of `astring.State.write` with two parameters, which doesn't appear to be supported by `astring` https://github.com/davidbonnet/astring/blob/6a856636c03543e657dd4fd868b9e6a4ed686bc1/src/astring.js#L1042-L1044
Is there some dynamic remapping of the `State` class I missed, or might https://github.com/davidbonnet/astring/blob/6a856636c03543e657dd4fd868b9e6a4ed686bc1/src/astring.js#L1050-L1058 be intended?

**Comment by wooorm** [comment]
The code for this is already PRed to upstream btw, so, depending on how long that’ll take, might be unneeded work.

I believe the `write` function accepts a node as a second parameter, which is used for source maps.
In my experiments though, astring isn’t great at source maps.

I think astring switches at runtime to use either the one without `node` if there is no SM support, or switches to the one with 2 params if SM is given

**Comment by ChristianMurphy** [comment]
Ah, you're right, there's a ternary overwrite in the constructor that replaces the method at runtime https://github.com/davidbonnet/astring/blob/6a856636c03543e657dd4fd868b9e6a4ed686bc1/src/astring.js#L1026-L1027
likely that means https://github.com/davidbonnet/astring/blob/6a856636c03543e657dd4fd868b9e6a4ed686bc1/astring.d.ts#L10 will need to be updated for this to be mergeable.

**Comment by wooorm** [comment]
ok, made this PR title more specific to astring.
I’d say it’s fine to not put too much focus into the astring code here. It’s running fine, and it’s mostly impaired by astring’s types

**Comment by wooorm** [comment]
Want to continue working on this and fix the CI error, or shall we close it and leave it to astring?

**Comment by ChristianMurphy** [comment]
Thanks for pinging!
Let's close this for now, and revisit when astring is ready

**Pull request closed without merging**
