### PR TITLE
Fix `MDXContent` to allow missing props

### LINKED ISSUE #82: Vue Router calls generated MDXContent function without props parameter, causing TypeError
---

### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 

Affected packages and versions: xdm@2.0.2

### Steps to reproduce

1. Download linked example (I spent too much time trying to get it running directly and gave up, sorry)
2. Run `npm install` or `yarn install`
3. Start app: `npm run serve` and open browser to 'localhost:8080'
4. Open web console
5. Note errors in the console pointing to trying to access components property on undefined

Link to code example: https://codesandbox.io/s/dank-tree-b1ubs

### Expected behavior

Should see output of `Page.mdx` underneath Vue logo
### Actual behavior

The content of Page.mdx is not shown. Error:
```
vue-router.esm-bundler.js?6c02:3264 TypeError: Cannot read properties of undefined (reading 'components')
    at MDXContent ...
```

### Notes
* I think adding a check or default to the generated function seems appropriate since all I'm seeing it used for is accessing components which may be an empty object anyways.
    * Something like:
     ```js
    function MDXContent(props = {}) {
      const _components = Object.assign({
        h1: "h1",
        p: "p"
      }, props && props.components), {wrapper: MDXLayout} = _components;
      const _content = ...
      return MDXLayout ? <MDXLayout {...props}>{_content}</MDXLayout> : _content;
    }
    export default MDXContent;
     ```
* I'm willing to help but I've never seen the unified/remark framework before so it will take some time to get up to speed.

### PR DESCRIPTION
**Pull request by mike-mcdonald**
Adjusts MDXContent function output to allow undefined props as a parameter without throwing a TypeError.

Closes #82

### CODE REVIEW

**Comment by wooorm** [comment]
Sweet, thanks for working on this!

I think it would be better to solve it in the argument list: `MDXContent(props = {})`.
Reasoning is that it’s documented that `props` is an object in one example of the readme: https://github.com/wooorm/xdm#mdx-content.

Also, could you update the example in the readme following “The actual output of running node example.js is:”?

There are also two errors in the tests on CI. the babel one looks a bit flakey (I’ll check if that’s still the case), but the error message might need to be changed?

**Comment by wooorm** [comment]
ps. run `npm test` locally to test your changes! And you can use ASTExplorer to figure out what the AST is for certain JS code

**Comment by wooorm** [comment]
Rebasing your PR against main should solve the weird babel error

**Comment by wooorm** [comment]
The other error was related due to a change in Node 16.9. Updates the tests to fix that as well.

**Comment by mike-mcdonald** [comment]
@wooorm Sounds like a plan. I'll adjust the fix to provide a default value for the props parameter and work on the test errors.

**Comment by mike-mcdonald** [comment]
@wooorm I've updated my branch with your changes to main and am able to run `npm run test` locally with no failures now!

**Review by wooorm — APPROVED** [review]

**Comment by wooorm** [comment]
Thanks, released!

**Pull request merged**
