### PR TITLE
Add next.js plugin

### PR DESCRIPTION
**Pull request by Zemnmez**
Adds a next.js plugin that exposes the webpack plugin.

### CODE REVIEW

**Comment by wooorm** [comment]
Heya! Thanks for the PR!

Have you seen the section in the readme? https://github.com/wooorm/xdm#next
It’s such a few lines of code, that I’m not sure whether it’s worthwhile to add a plugin.
Plus, now folks need to learn this plugin’s interface, instead of learning webpack + xdm.

**Comment by Zemnmez** [comment]
Oh! I didn't notice this in the readme somehow. The issue is that `webpack(config){}` you define there will clobber any other webpack config modifications any other plugins define. The plugin interface unfortunately has some sharp edges like that, and isn't all that well documented. Most next.js users I'd wager don't ever want to have to manually form / think about a webpack config -- especially since it's not intuitive how that plugin interface works.

**Comment by wooorm** [comment]
But this is how the next-mdx plugin works too? https://github.com/vercel/next.js/blob/canary/packages/next-mdx/index.js

**Comment by Zemnmez** [comment]
You're missing the last line that checks if the input object has a webpack field:
```javascript
module.exports = {
  // Support MDX files as pages:
  pageExtensions: ['mdx', 'tsx', 'ts', 'jsx', 'js'],
  // Support loading `.mdx`:
  webpack(config) {
    config.module.rules.push({
      test: /\.mdx$/,
      use: [{loader: 'xdm/webpack.cjs', options: {}}]
    })

    return config
  }
}
```

vs
```javascript
module.exports = (pluginOptions = {}) => (nextConfig = {}) => {
  const extension = pluginOptions.extension || /\.mdx$/

  return Object.assign({}, nextConfig, {
    webpack(config, options) {
      config.module.rules.push({
        test: extension,
        use: [
          options.defaultLoaders.babel,
          {
            loader: require.resolve('@mdx-js/loader'),
            options: pluginOptions.options,
          },
        ],
      })

      if (typeof nextConfig.webpack === 'function') { // <- this one
        return nextConfig.webpack(config, options)
      }

      return config
    },
  })
}
```

**Comment by wooorm** [comment]
That’s more about what else folks put in there though, no? And they still can do that? https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config

**Comment by Zemnmez** [comment]
Yeah, the only issue is that your example only tends to work if yours is the base config that all plugins are being added to.

If you are a next.js user and, for example, you use another example like the one that's in this repo, it's not immediately obvious how they are combined (by merging the webpack functions). It's fine if you're okay with that, it's just something I found rather hard when I was getting to know next.js -- adding this system then means understanding the plugin interface and understanding webpack.

**Comment by wooorm** [comment]
> Yeah, the only issue is that your example only tends to work if yours is the base config that all plugins are being added to.

I’m explicitly suggesting that folks add this to their `next.config.js`, so it should always be the base config?

>  It's fine if you're okay with that, it's just something I found rather hard when I was getting to know next.js

That’s understandable!

> adding this system then means understanding the plugin interface and understanding webpack.

The reason I prefer not adding plugins for every static site generator that exists (there are so many!!) is that I want to prevent an exponential gulp/grunt problem from happening. It’s hard to maintain those glue projects (e.g., this PR missing docs, tests, and won’t work at all because `xdm/package.json` is ESM). And it’s a superfluous (IMO) abstraction layer.
I want folks to learn about the two important layers: xdm and Next (or whatever else they want to use). Not *also* have to learn that layer in between

I appreciate your PR, but I think it makes more sense as docs where folks can copy/parse those few lines of code. Feel free to maintain it elsewhere though. And: docs improvements on xdm + Next are super welcome!

**Comment by Zemnmez** [comment]
> I’m explicitly suggesting that folks add this to their `next.config.js`, so it should always be the base config?

The tricky thing comes if you had, say two, like this:

```javascript
// suggested config A:
module.exports = {
  // Support MDX files as pages:
  pageExtensions: ['mdx', 'tsx', 'ts', 'jsx', 'js'],
  // Support loading `.mdx`:
  webpack(config) {
    // do some fancy stuff with webpack
   config.modules.yyy.doSomething();
   config.modules.xxx.doSomething();
    return config
  }
}
// suggested config B:
module.exports = {
  // Support MDX files as pages:
  pageExtensions: ['mdx', 'tsx', 'ts', 'jsx', 'js'],
  // Support loading `.mdx`:
  webpack(webPackConfigDifferentName) {
    webPackConfigDifferentName.module.rules.push({
      test: /\.mdx$/,
      use: [{loader: 'xdm/webpack.cjs', options: {}}]
    })

    return config
  }
}
```

Now, unless you understand webpack internals and the next.js plugin interface, it might not be obvious that you need to (1) rename the variable name, and (2) concat the two `webpack()` bodies to make this work.

I understand your reluctance to support all those, though. Just wanted to make sure it was understood :)

**Comment by wooorm** [comment]
Do you have an example of another integration? I can’t find `zemndm` and I’m not completely seeing the problem here

**Comment by Zemnmez** [comment]
Ah it’s okay. Maybe it’ll come up again, no worries!

**Pull request closed without merging**
